# Generated by Django 5.2.8 on 2025-11-22 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='テンプレート名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'フォームテンプレート',
                'verbose_name_plural': 'フォームテンプレート',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='質問文')),
                ('field_type', models.CharField(choices=[('text', 'テキスト (一行)'), ('textarea', 'テキスト (複数行)'), ('email', 'メールアドレス'), ('date', '日付'), ('number', '数値'), ('radio', 'ラジオボタン'), ('checkbox', 'チェックボックス'), ('file', 'ファイル')], max_length=20, verbose_name='入力形式')),
                ('options', models.JSONField(blank=True, help_text='ラジオボタンやチェックボックスの場合、["選択肢1", "選択肢2"] の形式で入力', null=True, verbose_name='選択肢')),
                ('is_required', models.BooleanField(default=True, verbose_name='必須項目')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='guest_forms.formtemplate', verbose_name='フォームテンプレート')),
            ],
            options={
                'verbose_name': 'フォーム項目',
                'verbose_name_plural': 'フォーム項目',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='施設名')),
                ('slug', models.SlugField(help_text="例: 'villa-sakura'", unique=True, verbose_name='URL識別子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest_forms.formtemplate', verbose_name='フォームテンプレート')),
            ],
            options={
                'verbose_name': '施設',
                'verbose_name_plural': '施設',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='チェックイン日')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='予約者メールアドレス')),
                ('guest_name', models.CharField(max_length=255, verbose_name='予約者名')),
                ('guest_roster_status', models.CharField(choices=[('pending', '未提出'), ('submitted', '提出済'), ('verified', '確認済')], default='pending', max_length=20, verbose_name='名簿提出状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guest_forms.property', verbose_name='施設')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'unique_together': {('property', 'check_in_date')},
            },
        ),
        migrations.CreateModel(
            name='GuestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='フォームアクセス用トークン')),
                ('status', models.CharField(choices=[('pending', '入力待'), ('completed', '提出完了')], default='pending', max_length=20, verbose_name='提出状況')),
                ('submitted_data', models.JSONField(blank=True, null=True, verbose_name='提出データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guest_forms.reservation', verbose_name='予約')),
            ],
            options={
                'verbose_name': '名簿提出内容',
                'verbose_name_plural': '名簿提出内容',
            },
        ),
    ]
