# Generated by Django 5.2.8 on 2025-11-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='beds24_property_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Beds24プロパティキー'),
        ),
    ]
