# Generated by Django 5.2.8 on 2025-11-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0002_alter_property_beds24_property_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='アメニティ名')),
            ],
            options={
                'verbose_name': 'アメニティ',
                'verbose_name_plural': 'アメニティ',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='guest_forms.amenity', verbose_name='アメニティ'),
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000, verbose_name='画像URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guest_forms.property', verbose_name='施設')),
            ],
            options={
                'verbose_name': '施設画像',
                'verbose_name_plural': '施設画像',
                'ordering': ['order'],
            },
        ),
    ]
