# Generated by Django 5.2.8 on 2025-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0003_amenity_property_amenities_facilityimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-check_in_date'], 'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='beds24_book_id',
            field=models.IntegerField(help_text="Beds24の'bookId'", null=True, unique=True, verbose_name='Beds24予約ID'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(help_text="Beds24の'Last Night'", null=True, verbose_name='チェックアウト日'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_guests',
            field=models.IntegerField(default=1, help_text="Beds24の'Number of Guests'", verbose_name='宿泊者数'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, help_text="Beds24の'Status'", max_length=50, null=True, verbose_name='予約ステータス'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Beds24の'Price'", max_digits=10, verbose_name='合計料金'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(help_text="Beds24の'First Night'", verbose_name='チェックイン日'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='予約者メールアドレス'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, help_text="Beds24の'Guest Name'", max_length=255, null=True, verbose_name='予約者名'),
        ),
    ]
