# Generated by Django 5.2.8 on 2025-11-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0004_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='property',
        ),
    ]
