# Generated by Django 5.2.8 on 2025-11-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0005_remove_reservation_property'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsubmission',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='予約'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
