# Generated by Django 5.2.8 on 2025-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0006_alter_guestsubmission_reservation_delete_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='facilityimage',
            name='image',
            field=models.ImageField(default='', upload_to='facility_images/', verbose_name='画像ファイル'),
            preserve_default=False,
        ),
    ]
