# Generated by Django 5.2.8 on 2025-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_forms', '0007_remove_facilityimage_image_url_facilityimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='faq',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True, verbose_name='ハウスルール'),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_info',
            field=models.TextField(blank=True, verbose_name='Wi-Fi情報'),
        ),
    ]
