# Generated by Django 5.2.8 on 2025-12-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0009_add_pricing_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestsubmission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pricingrule",
            options={
                "verbose_name": "名簿提出内容",
                "verbose_name_plural": "名簿提出内容",
            },
        ),
        migrations.RemoveIndex(
            model_name="pricingrule",
            name="guest_forms_property_date_idx",
        ),
        migrations.AlterUniqueTogether(
            name="pricingrule",
            unique_together=set(),
        ),
    ]
