# Generated by Django 5.2.8 on 2025-11-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_forms', '0005_remove_reservation_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync_time', models.DateTimeField(verbose_name='最終同期時刻')),
            ],
            options={
                'verbose_name': '同期ステータス',
                'verbose_name_plural': '同期ステータス',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds24_book_id', models.IntegerField(help_text="Beds24の'bookId'", null=True, unique=True, verbose_name='Beds24予約ID')),
                ('status', models.CharField(blank=True, help_text="Beds24の'Status'", max_length=50, null=True, verbose_name='予約ステータス')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text="Beds24の'Price'", max_digits=10, verbose_name='合計料金')),
                ('check_in_date', models.DateField(help_text="Beds24の'First Night'", verbose_name='チェックイン日')),
                ('check_out_date', models.DateField(help_text="Beds24の'Last Night'", null=True, verbose_name='チェックアウト日')),
                ('num_guests', models.IntegerField(default=1, help_text="Beds24の'Number of Guests'", verbose_name='宿泊者数')),
                ('guest_name', models.CharField(blank=True, help_text="Beds24の'Guest Name'", max_length=255, null=True, verbose_name='予約者名')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='予約者メールアドレス')),
                ('guest_roster_status', models.CharField(choices=[('pending', '未提出'), ('submitted', '提出済'), ('verified', '確認済')], default='pending', max_length=20, verbose_name='名簿提出状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='guest_forms.property', verbose_name='施設')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-check_in_date'],
            },
        ),
    ]
