# Generated by Django 5.2.8 on 2025-12-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("accommodation", "宿泊税"), ("prefectural", "道税")],
                        default="accommodation",
                        max_length=20,
                        verbose_name="税種",
                    ),
                ),
                ("num_nights", models.IntegerField(default=1, verbose_name="宿泊日数")),
                (
                    "tax_rate",
                    models.IntegerField(default=100, verbose_name="税率（¥/泊）"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="納税額（¥）",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "未払い"),
                            ("paid", "支払済"),
                            ("exempted", "免除"),
                            ("deferred", "延期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支払い状況",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "現金"),
                            ("card", "クレジットカード"),
                            ("stripe", "Stripe"),
                            ("bank_transfer", "銀行振込"),
                            ("other", "その他"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="支払い方法",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="支払日"),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="支払い参照番号（Stripe Transaction ID等）",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_tax",
                        to="reservations.reservation",
                        verbose_name="予約",
                    ),
                ),
            ],
            options={
                "verbose_name": "宿泊税",
                "verbose_name_plural": "宿泊税",
                "ordering": ["-created_at"],
            },
        ),
    ]
