# Generated by Django 5.2.8 on 2025-12-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_forms", "0010_alter_guestsubmission_options_and_more"),
        ("reservations", "0002_accommodationtax"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1泊あたりの基本料金",
                        max_digits=10,
                        null=True,
                        verbose_name="基本料金",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True,
                        help_text="この日が予約可能かどうか",
                        verbose_name="予約可能",
                    ),
                ),
                (
                    "min_stay",
                    models.IntegerField(
                        default=1,
                        help_text="この日からの最小宿泊数",
                        verbose_name="最小宿泊数",
                    ),
                ),
                (
                    "beds24_data",
                    models.JSONField(
                        blank=True,
                        help_text="Beds24 APIから取得した元データ",
                        null=True,
                        verbose_name="Beds24生データ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_rates",
                        to="guest_forms.property",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "日別料金",
                "verbose_name_plural": "日別料金",
                "ordering": ["property", "date"],
                "indexes": [
                    models.Index(
                        fields=["property", "date"],
                        name="reservation_propert_f09929_idx",
                    ),
                    models.Index(fields=["date"], name="reservation_date_e2f136_idx"),
                ],
                "unique_together": {("property", "date")},
            },
        ),
    ]
