# Generated by Django 5.2.8 on 2025-12-07 05:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="イベント名")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FESTIVAL", "祭り"),
                            ("SEASONAL", "季節イベント"),
                            ("CULTURAL", "文化イベント"),
                            ("SPORTS", "スポーツイベント"),
                            ("MARKET", "市場・マルシェ"),
                            ("OTHER", "その他"),
                        ],
                        max_length=20,
                        verbose_name="イベント種別",
                    ),
                ),
                ("description", models.TextField(verbose_name="説明")),
                ("venue", models.CharField(max_length=300, verbose_name="開催場所")),
                (
                    "address",
                    models.CharField(blank=True, max_length=300, verbose_name="住所"),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時刻"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="終了時刻"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="毎年同じ時期に開催されるイベント",
                        verbose_name="毎年開催",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="問い合わせ先"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="公式サイトURL",
                    ),
                ),
                (
                    "admission_fee",
                    models.CharField(
                        blank=True,
                        help_text="例: 無料、1000円など",
                        max_length=200,
                        verbose_name="参加費",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/events/",
                        verbose_name="画像",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="公開中")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "イベント",
                "verbose_name_plural": "イベント",
                "ordering": ["start_date", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TouristAttraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="施設名")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HISTORIC", "歴史的建造物"),
                            ("NATURE", "自然・景観"),
                            ("MUSEUM", "博物館・美術館"),
                            ("SHOPPING", "ショッピング"),
                            ("HOT_SPRING", "温泉"),
                            ("FOOD", "グルメ・市場"),
                            ("OTHER", "その他"),
                        ],
                        max_length=20,
                        verbose_name="カテゴリー",
                    ),
                ),
                ("description", models.TextField(verbose_name="説明")),
                ("address", models.CharField(max_length=300, verbose_name="住所")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="緯度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="経度",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="ウェブサイトURL",
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="例: 9:00-17:00 (休館日: 月曜日)",
                        verbose_name="営業時間",
                    ),
                ),
                (
                    "admission_fee",
                    models.CharField(
                        blank=True,
                        help_text="例: 大人500円、子供300円",
                        max_length=200,
                        verbose_name="入場料",
                    ),
                ),
                (
                    "access_info",
                    models.TextField(blank=True, verbose_name="アクセス情報"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/attractions/",
                        verbose_name="画像",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="公開中")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "観光施設",
                "verbose_name_plural": "観光施設",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("SPRING", "春 (3-5月)"),
                            ("SUMMER", "夏 (6-8月)"),
                            ("AUTUMN", "秋 (9-11月)"),
                            ("WINTER", "冬 (12-2月)"),
                        ],
                        max_length=10,
                        verbose_name="季節",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/seasonal/",
                        verbose_name="画像",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="公開中")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "related_events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seasonal_recommendations",
                        to="tourism.event",
                        verbose_name="関連するイベント",
                    ),
                ),
                (
                    "related_attractions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seasonal_recommendations",
                        to="tourism.touristattraction",
                        verbose_name="関連する観光施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "季節のおすすめ",
                "verbose_name_plural": "季節のおすすめ",
                "ordering": ["display_order", "season"],
            },
        ),
    ]
